name: wsafe
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.7.0
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  flutter_native_contact_picker: ^0.0.4
  flutter_sms: ^2.3.3
  flutter_spinkit: ^5.2.0
  location: ^4.4.0
  permission_handler: ^10.2.0
  provider: ^6.0.5
  settings_ui: ^2.0.2
  shared_preferences: ^2.1.1
  sliding_clipped_nav_bar: ^3.1.0+4
  flutter_background: ^1.2.0
  shake: ^2.2.0
  app_to_foreground: ^0.0.3

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/"
